version: '3.9'

services:
  rebuy-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: rebuy-app
    restart: always
    ports:
      - "8001:8001"
    volumes:
      - .:/var/www/html
    depends_on:
      - rebuy-db

  rebuy-db:
    image: postgres:14-alpine
    container_name: rebuy-db
    restart: always
    command: postgres
    volumes:
      - .ops/data/:/var/lib/postgresql/
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger_ui_container
    ports:
      - "8082:8080"
    volumes:
      - ./docs/contracts:/docs
    environment:
      SWAGGER_JSON: '/docs/api.yaml'
    depends_on:
      - rebuy-app
